add encryption setup

diff --git a/.github/workflows/score_submission.yml b/.github/workflows/score_submission.yml
--- a/.github/workflows/score_submission.yml
+++ b/.github/workflows/score_submission.yml
@@ -35,8 +35,9 @@ jobs:
           echo "Files found:"
           echo "$FILES"
 
-          EXPECTED1="submissions/predictions.csv"
-          EXPECTED2="submissions/metadata.json"
+          EXPECTED1="submissions/predictions.csv.enc"
+          EXPECTED2="submissions/secret.key.enc"
+          EXPECTED3="submissions/metadata.json"
 
           COUNT=$(echo "$FILES" | wc -l)
 
@@ -46,11 +47,16 @@ jobs:
           fi
 
           if ! echo "$FILES" | grep -qx "$EXPECTED1"; then
-            echo "❌ Missing submissions/predictions.csv"
+            echo "❌ Missing submissions/predictions.csv.enc"
             exit 1
           fi
 
           if ! echo "$FILES" | grep -qx "$EXPECTED2"; then
+            echo "❌ Missing submissions/secret.key.enc"
+            exit 1
+          fi
+
+          if ! echo "$FILES" | grep -qx "$EXPECTED3"; then
             echo "❌ Missing submissions/metadata.json"
             exit 1
           fi
@@ -60,7 +66,8 @@ jobs:
       # 4️⃣ Checkout only the required submission files
       - name: Checkout submission files
         run: |
-          git checkout pr -- submissions/predictions.csv
+          git checkout pr -- submissions/predictions.csv.enc
+          git checkout pr -- submissions/secret.key.enc
           git checkout pr -- submissions/metadata.json
 
       # 5️⃣ Set up Python
@@ -73,6 +80,26 @@ jobs:
       - name: Install dependencies
         run: |
           pip install pandas pyarrow scikit-learn
+
+      # Decrypt submission
+      - name: Decrypt submission
+        env:
+          PRIVATE_KEY: ${{ secrets.DECRYPT_KEY }}
+        run: |
+          # 1. Create the private key file temporarily in extra/
+          cat <<"EOF" > extra/private.pem
+          $PRIVATE_KEY
+          EOF
+          
+          # 2. Decrypt the symmetric key from submissions/
+          openssl pkeyutl -decrypt -inkey extra/private.pem -in submissions/secret.key.enc -out extra/key.txt
+          
+          # 3. Decrypt the CSV from submissions/
+          openssl enc -d -aes-256-cbc -in submissions/predictions.csv.enc -out predictions.csv -pass file:extra/key.txt -pbkdf2
+          
+          # 4. Immediate cleanup
+          rm extra/private.pem extra/key.txt
+
 
       # 7️⃣ Clone private labels repo
       - name: Clone private labels repo
